server:
  port: 8090
spring:
  application:
    name: rabbitmq-consumer
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: root
    virtual-host: twy
    # 手动确认消息
    listener:
      simple:
        acknowledge-mode: manual